IMAGE_SIZE = (32, 32)
PATCH_SIZE = (4, 4)
CHANNELS = 3
DIM_EMBED = 128
DIM_MLP = 4 * DIM_EMBED # 512, 256
NUM_HEAD = 4 # 12 in the original
NUM_TRANSFORMER = 6 # depth, 12 in the original
NUM_CLASSES = 10
DROPOUT_RATE = 0.1 
LOCAT = True
TASK = "classif"
DPR = 0.1 # 0. for no drop_path
BIAS = False
PIN_MEMORY = False
NUM_WORKERS = 4